### ISSUE TITLE
Content-Length보다 실제 바디가 클 경우에 대한 처리는 어떻게 돼야할까요?

### ISSUE THREAD

**Issue by hyeonski** [42seoul-NULL/Webserv_#16]
Request가 하나의 read에 여러 개 들어오는 case에 대해 점검 중입니다.
message.append("GET /index.html HTTP/1.1\r\n");
message.append("Host: localhost\r\n");
message.append("User-Agent: tester\r\n");
message.append("Connection: keep-alive\r\n");
message.append("Content-Length: 16\r\n");
message.append("\r\n");
message.append("body\r\n");
message.append("body\r\n");
message.append("body extra-body");
message.append("GET / HTTP/1.1\r\n");
message.append("Host: localhost\r\n");
message.append("User-Agent: tester\r\n");
message.append("Connection: keep-alive\r\n");
message.append("\r\n");

이런 형태로 content-length보다 큰 바디가 들어왔을 경우 다음 리퀘스트 파싱이 불가능해지는데, 무시하고 할지 처리해주어야 하는 부분일지 논의가 필요합니당..

**Comment by dev2l0per** [comment]
https://stackoverflow.com/questions/8314051/what-to-do-if-http-content-length-differs-from-actual-body-size

큰 바디에 대해서 400 Bad Request 를 처리하는게 더 좋을 경우가 될 것 같습니다.

Request를 통해 CGI에게 넘겨야 하는 정보가 잘리게 되버리면, 오히려 취약점으로써 작동을 할 수도 있을 것 같습니다.

**Comment by hyeonski** [comment]
스타트 라인을 이용한 판정으로 할 수 있다는 대책만 세워두고, 일단 이슈 닫겠습니다! 이후 다시 논의하는 것으로 할게요.
